version: '3.9'
services:
  database:
    image: postgres:14.5-alpine
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=admin
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432